# Generated by Django 4.2.17 on 2026-01-13 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('SMALL', 'Small Animal'), ('LARGE', 'Large Animal')], help_text='Type of animal (small or large)', max_length=10)),
                ('breed', models.CharField(help_text='Breed of the animal', max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age of the animal in months')),
                ('weight', models.PositiveIntegerField(help_text='Weight of the animal in kilograms')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in currency', max_digits=10)),
                ('location', models.CharField(help_text='Location of the animal', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the animal')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this listing is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(help_text='User who created this listing', on_delete=django.db.models.deletion.CASCADE, related_name='animal_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'animal listing',
                'verbose_name_plural': 'animal listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
