# Generated by Django 4.2.17 on 2026-01-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file', upload_to='animal_images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='The animal listing this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.animallisting')),
            ],
            options={
                'verbose_name': 'animal image',
                'verbose_name_plural': 'animal images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
