# Generated by Django 4.2.17 on 2026-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_update_animal_types_to_turkish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallisting',
            name='age',
            field=models.IntegerField(blank=True, help_text='Hayvanın yaşı (ay cinsinden)', null=True, verbose_name='Yaş (ay)'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='animal_type',
            field=models.CharField(choices=[('KUCUKBAS', 'Küçükbaş'), ('BUYUKBAS', 'Büyükbaş')], help_text='Küçükbaş veya Büyükbaş', max_length=10, verbose_name='Hayvan Türü'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='breed',
            field=models.CharField(help_text='Hayvanın cinsi (örn: Merinos, Kıvırcık)', max_length=100, verbose_name='Cins'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='description',
            field=models.TextField(blank=True, help_text='İlan detayları (isteğe bağlı)', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='location',
            field=models.CharField(help_text='İlanın bulunduğu şehir/bölge', max_length=200, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Satış fiyatı (TL)', max_digits=10, verbose_name='Fiyat (TL)'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tahmini ağırlık (kg)', max_digits=6, null=True, verbose_name='Ağırlık (kg)'),
        ),
    ]
