# Generated by Django 4.2.17 on 2026-01-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animallisting_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallisting',
            name='age_months',
            field=models.IntegerField(blank=True, help_text='Hayvanın yaşı (ay cinsinden)', null=True, verbose_name='Yaş (ay)'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='city',
            field=models.CharField(blank=True, help_text="Şehir (dropdown'dan seçilir)", max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='company',
            field=models.CharField(blank=True, default='', help_text='İlan sahibinin şirketi (opsiyonel)', max_length=200, verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='district',
            field=models.CharField(blank=True, help_text="İlçe (dropdown'dan seçilir)", max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='ear_tag_no',
            field=models.CharField(blank=True, help_text='Hayvanın kulak numarası (opsiyonel, benzersiz)', max_length=50, null=True, unique=True, verbose_name='Kulak No'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='gender',
            field=models.CharField(blank=True, choices=[('ERKEK', 'Erkek'), ('DISI', 'Dişi')], help_text='Hayvanın cinsiyeti (opsiyonel)', max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='species',
            field=models.CharField(blank=True, choices=[('KOYUN', 'Koyun'), ('KECI', 'Keçi'), ('DANA', 'Dana'), ('INEK', 'İnek')], help_text='Hayvan türü: Koyun, Keçi, Dana, İnek', max_length=20, null=True, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='age',
            field=models.IntegerField(blank=True, help_text='Eski yaş alanı (ay cinsine dönüştürülecek)', null=True, verbose_name='Yaş (yıl - eski)'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='animal_type',
            field=models.CharField(choices=[('SMALL', 'Küçükbaş'), ('BUYUKBAS', 'Büyükbaş')], help_text='Küçükbaş veya Büyükbaş (otomatik belirlenir)', max_length=10, verbose_name='Hayvan Grubu'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='breed',
            field=models.CharField(blank=True, default='', help_text='Hayvanın ırkı (opsiyonel, örn: Merinos, Kıvırcık)', max_length=100, verbose_name='Irk'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='location',
            field=models.CharField(blank=True, help_text='İlanın bulunduğu şehir/bölge (backward compat)', max_length=200, null=True, verbose_name='Konum (eski)'),
        ),
    ]
