# Generated by Django 4.2.17 on 2026-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_migrate_age_to_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallisting',
            name='title',
            field=models.CharField(blank=True, default='', help_text='İlan başlığı (örn: Satılık Kurbanlık Koç)', max_length=100, verbose_name='İlan Başlığı'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='breed',
            field=models.CharField(blank=True, default='', help_text='Hayvanın ırkı (opsiyonel, örn: Merinos, Kıvırcık)', max_length=100, null=True, verbose_name='Irk'),
        ),
    ]
