# Generated by Django 4.2.17 on 2026-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animallisting_title_alter_animallisting_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallisting',
            name='species',
            field=models.CharField(blank=True, help_text='Hayvan türü (örn: Koyun, Keçi, Dana)', max_length=50, null=True, verbose_name='Tür'),
        ),
    ]
