# Generated by Django 4.2.17 on 2026-01-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_animalimage_order_alter_animalimage_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'animal image', 'verbose_name_plural': 'animal images'},
        ),
    ]
