# Generated by Django 4.2.17 on 2026-02-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_alter_animalimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallisting',
            name='breed',
            field=models.CharField(blank=True, default='', help_text='Hayvan türü (Koyun, Keçi, Dana, Tosun vb.)', max_length=100, null=True, verbose_name='Hayvan Türü'),
        ),
    ]
