# Generated by Django 4.2.17 on 2026-01-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchers', '0003_butcherprofile_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butcherprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='butcherprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='butcherprofile',
            name='district',
            field=models.CharField(blank=True, default='', help_text='İlçe (opsiyonel)', max_length=100),
        ),
        migrations.AddField(
            model_name='butcherprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Kasabın adı', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='butcherprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Kasabın soyadı', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='butcherprofile',
            name='city',
            field=models.CharField(help_text='Şehir (zorunlu)', max_length=100),
        ),
        migrations.AlterField(
            model_name='butcherprofile',
            name='price_range',
            field=models.CharField(blank=True, default='', help_text="Price range (e.g., '500-1000')", max_length=50),
        ),
    ]
