# Generated by Django 4.2.17 on 2026-01-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butchers', '0004_update_butcher_profile_fields'),
    ]

    operations = [
    ]
