# Generated by Django 4.2.17 on 2026-01-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ANIMAL', 'Animal Listing'), ('SELLER', 'Seller'), ('BUTCHER', 'Butcher')], help_text='Type of recommendation', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the recommended object')),
                ('score', models.FloatField(help_text='Relevance score (higher is better)')),
                ('reason', models.CharField(help_text='Short explanation for the recommendation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who receives this recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendations',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-score', '-created_at'], name='recommendat_user_id_e80c85_idx'), models.Index(fields=['user', 'type'], name='recommendat_user_id_fbd449_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'object_id'), name='unique_recommendation'),
        ),
    ]
