# Generated by Django 4.2.17 on 2026-02-01 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_alter_animallisting_breed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Viewed Listing'), ('PHONE_CLICK', 'Clicked Phone'), ('WHATSAPP_CLICK', 'Clicked WhatsApp'), ('FAVORITE', 'Favorited')], default='VIEW', help_text='Type of interaction', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for anonymous user tracking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='The listing that was interacted with', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='animals.animallisting')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the interaction (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'listing interaction',
                'verbose_name_plural': 'listing interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='recommendat_user_id_53c208_idx'), models.Index(fields=['listing', 'interaction_type'], name='recommendat_listing_71cd4e_idx'), models.Index(fields=['ip_address', 'created_at'], name='recommendat_ip_addr_1554fe_idx')],
            },
        ),
    ]
