# Generated by Django 5.1.7 on 2025-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
