# Generated by Django 5.1.7 on 2025-07-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stok Miktarı'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('available', 'Stokta Var'), ('limited', 'Sınırlı Stok'), ('out', 'Stokta Yok')], default='available', max_length=20, verbose_name='Stok Durumu'),
        ),
    ]
