# Generated by Django 4.2.23 on 2025-08-04 01:19

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_product_stock_quantity_product_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[pages.models.validate_file_size, pages.models.validate_image_extension], verbose_name='Banner Resmi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/', validators=[pages.models.validate_file_size, pages.models.validate_image_extension], verbose_name='Kategori Resmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[pages.models.validate_file_size, pages.models.validate_image_extension], verbose_name='Ürün Resmi'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[pages.models.validate_file_size, pages.models.validate_image_extension], verbose_name='Ürün Resmi'),
        ),
    ]
