# Generated by Django 4.2.17 on 2026-04-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0012_alter_animallisting_breed'),
        ('chat_messages', '0003_groupconversation_groupmessage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='buyer',
            field=models.ForeignKey(help_text='The buyer or client in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='The animal listing being discussed (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='animals.animallisting'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='seller',
            field=models.ForeignKey(help_text='The seller or service provider in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('listing', 'buyer'), name='unique_listing_buyer_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', True)), fields=('buyer', 'seller'), name='unique_general_conversation'),
        ),
    ]
