# Generated by Django 4.2.17 on 2026-04-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0004_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='The message being replied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat_messages.groupmessage'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='The message being replied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat_messages.message'),
        ),
    ]
