# Generated by Django 4.2.17 on 2026-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0005_groupmessage_parent_message_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether message has been deleted for everyone'),
        ),
    ]
