# Generated by Django 4.2.17 on 2026-04-04 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0006_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have deleted this message for themselves', related_name='deleted_group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether message has been deleted for everyone'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have deleted this message for themselves', related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
