# Generated by Django 4.2.17 on 2026-04-10 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0007_groupmessage_deleted_by_groupmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have hidden/deleted this conversation from their inbox', related_name='deleted_direct_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupconversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have hidden/deleted this group conversation from their inbox', related_name='deleted_group_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
