# Generated by Django 4.2.17 on 2026-01-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='TR', help_text='Country code for location context (e.g., TR, DE)', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Contact phone number (free-form)', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Unique username (lowercase, alphanumeric + underscore)', max_length=30, null=True, unique=True),
        ),
    ]
