# Generated by Django

from django.db import migrations
import re


def generate_username_from_email(email):
    """
    Generate username from email prefix.
    - Extract part before @
    - Normalize (lowercase, alphanumeric + underscore)
    - Ensure starts with letter
    - Trim to 30 chars
    """
    prefix = email.split('@')[0]
    # Lowercase
    normalized = prefix.lower().strip()
    # Replace invalid chars with underscore
    normalized = re.sub(r'[^a-z0-9_]', '_', normalized)
    # Ensure starts with letter
    if not normalized or not normalized[0].isalpha():
        normalized = 'u_' + normalized
    # Trim to 30
    normalized = normalized[:30]
    # Ensure minimum length
    if len(normalized) < 3:
        normalized = normalized + '_user'
    
    return normalized


def populate_usernames(apps, schema_editor):
    """
    Populate username field for all existing users based on email prefix.
    Handle conflicts by appending _2, _3, etc.
    """
    User = apps.get_model('accounts', 'User')
    
    used_usernames = set()
    
    for user in User.objects.all():
        if user.username:
            # Already has username
            used_usernames.add(user.username)
            continue
        
        # Generate base username
        base_username = generate_username_from_email(user.email)
        username = base_username
        suffix = 2
        
        # Handle conflicts
        while username in used_usernames:
            username = f"{base_username}_{suffix}"
            # Ensure still within 30 char limit
            if len(username) > 30:
                base_username = base_username[:27]  # Leave room for _XX
                username = f"{base_username}_{suffix}"
            suffix += 1
        
        user.username = username
        used_usernames.add(username)
        user.save()
        
        print(f"Generated username '{username}' for {user.email}")


def reverse_populate(apps, schema_editor):
    """Reverse migration: set all usernames to None"""
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(username=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_profile_fields'),
    ]

    operations = [
        migrations.RunPython(populate_usernames, reverse_populate),
    ]
