# Generated by Django 4.2.17 on 2026-03-21 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('butchers', '0006_populate_real_butcher_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButcherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating between 1 (worst) and 5 (best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='', help_text='Optional written comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('butcher', models.ForeignKey(help_text='The butcher being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='butchers.butcherprofile')),
                ('user', models.ForeignKey(help_text='Customer who left the review', on_delete=django.db.models.deletion.CASCADE, related_name='butcher_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'butcher review',
                'verbose_name_plural': 'butcher reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['butcher', '-created_at'], name='reviews_but_butcher_5984c9_idx'), models.Index(fields=['user', '-created_at'], name='reviews_but_user_id_11cf37_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='butcherreview',
            constraint=models.UniqueConstraint(fields=('butcher', 'user'), name='unique_review_per_user_per_butcher'),
        ),
    ]
