name: KurbanLink Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to AWS Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/KurbanLink
            git pull origin main
            
            # Backend Güncelleme
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --noinput
            pm2 restart kurban-backend
            
            # Frontend Güncelleme
            cd ../frontend
            npm install
            
            # Localhost temizliği
            find src -type f -exec sed -i 's|http://localhost:8000|https://kurbanlink.com|g' {} +
            
            # Build ve Restart
            npm run build
            pm2 restart kurban-frontend